### ISSUE TITLE
Optimization for pow

### ISSUE THREAD

**Issue by neobrain** [machinamentum/Caelina#1]
`vertex_lighting_3ds.vsh` implements a power function (calculating `r0.x ^ r1.x` for lighting using a loop. This is fairly inefficient, and can be done a lot more easily by using the identity `r0.x ^ r1.x = (2 ^ ld r0.x)^r1.x = 2 ^ (r1.x * ld r0.x)` (with ld the base-2 logarithm):

```
// NOTE: r2 is changed in this function
pow:
    log r2.x, r0.x
    mul r2.x, r2.x, r1.x
    exp r0.x, r2.x
    nop
end_pow:
```

Figured I'd just throw this out here ;)

**Comment by machinamentum** [comment]
Actually, the algorithm calculates r0.xyzw ^ r1.x because yzw do not always have to equal x. This is definitely the neatest optimization I've ever seen, I'll add it in after a few short tests.

**Comment by machinamentum** [comment]
Added in ea9eef9b4b341d420d57117bb61d488a9c1331a3. Thank you.

**Comment by neobrain** [comment]
No problem, glad I could help ;)

**Comment by machinamentum** [comment]
It helps a lot actually. The shader isn't super slow in Citra now. With the old shader, one frame could take up to 30 seconds, with this, it's closer to about a second :)
