### ISSUE TITLE
OpenGL version

### ISSUE THREAD

**Issue by Lectem** [machinamentum/Caelina#2]
I would like to know if you are planning to change the opengl version of Caelina. I'm asking this because OpenGL 1.1 is a bit wrong, since the PICA200 supports OpenGL ES 1.0 (and most of OES 2). I'm also thinking about things such as texture combiners (https://www.opengl.org/wiki/Texture_Combiners) that were added only since OpenGL 1.3.

I'm also thinking about the texture clamping https://github.com/machinamentum/Caelina/blob/master/libcaelina/source/driver_3ds.cpp#L170 and many other things that are not available in ogl1.1.

I think that switching to OES1.1 however would be a good idea, and shouldn't involve much work.

**Comment by machinamentum** [comment]
Please remember that OES is considered a set of subsets of desktop GL. Supporting desktop GL functionality inherently means supporting GL ES functionality. Therefore, switching to a purely OES specification would be considered a downgrade. That being said, the plan is to implement as much of GL 1.1 as possible then support for newer specifications will be added, as well as adding OES headers and functions.

**Comment by Lectem** [comment]
Ok, guess I will wait before contributing then, since most of the stuff I worked on is only available after 1.3 or 1.4. Thanks for the clarification

**Comment by machinamentum** [comment]
You are welcome to contribute anything not specified in GL 1.1 as long as it adheres to OpenGL's specification and the conventions currently in use in the implementation. Note that any functions added must check if g_state is null, check if it isn't allowed in glBegin/glEnd blocks, and if it can be cached into a display list, it must add itself to the currently compiling list and be called by executeList. Most importantly, it mustn't break other functions.

**Comment by Lectem** [comment]
What about the missing defines? What value should those take and where should those be added?

**Comment by machinamentum** [comment]
Some defines are missing because Mesa3D's gl.h depends on Khronos' glext.h. Download the official glext.h and check if the defines are in there first. Currently, the glext.h being used just defines glScissorMode, which should be moved out into a different header since it isn't an official extension.

**Comment by machinamentum** [comment]
I've decided to include Khronos' glext.h, and any "unregistered extensions" such as the PICA200's inverted scissor mode will be added to GL/ctr.h

**Comment by Lectem** [comment]
I'm starting to think we should implement our own glext.h, according to https://www.opengl.org/registry : /#headers <GL/glext.h> - OpenGL 1.2 and above compatibility profile and extension interfaces.

Most of what I saw in the Khronos header would be vendor specific anyway.

**Comment by machinamentum** [comment]
Please see the [implementor's guide](https://www.khronos.org/registry/implementers_guide.html). Khronos specifies using their glext.h and any of the implementor's extensions that aren't registered must be placed into the implementor's own headers.

**Comment by Lectem** [comment]
Oh, right. Guess this answers all my questions then ! Thanks.
