### ISSUE TITLE
nehe/lesson06 doesn't draw png

### ISSUE THREAD

**Issue by krruzic** [machinamentum/Caelina#7]
Not sure how to debug this as I have no idea what I'm doing.... anyway, compiles fine and runs fine, but the cube doesn't have the image on it.

**Comment by machinamentum** [comment]
1393cbdffeb1c401bcc63c2c5f976b2c0bd2b3b6 should fix this. Seems like romfs has changed to not support relative paths.

**Comment by krruzic** [comment]
thanks man!
